import { displayName, type MatchResult } from '../state/store';
import { composeAvatarSheet, Animation, SPRITE_W, SPRITE_H } from '../avatar/compose';

/**
 * Render the final draft board to a PNG blob. Separate from the React DOM
 * results screen so the export looks clean and shareable (no buttons, no
 * scroll, fixed dimensions) — also avoids needing html2canvas.
 *
 * Returns null if canvas creation fails (rare; defensive).
 */
export function renderResultsPng(result: MatchResult): Promise<Blob | null> {
  return new Promise((resolve) => {
    const SCALE = 2;
    const WIDTH = 480;
    const ROW_HEIGHT = 56;
    const PADDING = 24;
    const HEADER = 72;
    const FOOTER = 56;
    const HEIGHT = HEADER + ROW_HEIGHT * result.roster.length + FOOTER;

    const canvas = document.createElement('canvas');
    canvas.width = WIDTH * SCALE;
    canvas.height = HEIGHT * SCALE;
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      resolve(null);
      return;
    }
    ctx.scale(SCALE, SCALE);
    ctx.imageSmoothingEnabled = false;

    // Background
    ctx.fillStyle = '#0a0a14';
    ctx.fillRect(0, 0, WIDTH, HEIGHT);

    // Border
    ctx.strokeStyle = '#2d2d55';
    ctx.lineWidth = 4;
    ctx.strokeRect(2, 2, WIDTH - 4, HEIGHT - 4);

    // Header
    ctx.fillStyle = '#ffcc00';
    ctx.font = 'bold 28px ui-monospace, monospace';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('DRAFT ORDER', WIDTH / 2, 36);
    ctx.font = '12px ui-monospace, monospace';
    ctx.fillStyle = '#9090b8';
    ctx.fillText(`seed: ${result.seed}`, WIDTH / 2, 58);

    // Bake all 12 sprite sheets up front so the draw loop is just blits.
    const sheets = new Map<number, HTMLCanvasElement>();
    for (const p of result.roster) sheets.set(p.id, composeAvatarSheet(p.avatar));

    // Rows
    const board = result.eliminationOrder
      .map((wrestlerId, eliminationIndex) => ({
        wrestlerId,
        pickNumber: result.roster.length - eliminationIndex,
      }))
      .sort((a, b) => a.pickNumber - b.pickNumber);

    board.forEach((row, i) => {
      const y = HEADER + i * ROW_HEIGHT;
      const isWinner = row.pickNumber === 1;
      const player = result.roster[row.wrestlerId];
      const sheet = sheets.get(row.wrestlerId);

      // Row background
      ctx.fillStyle = isWinner ? 'rgba(255, 204, 0, 0.12)' : '#15152a';
      ctx.fillRect(PADDING, y + 4, WIDTH - 2 * PADDING, ROW_HEIGHT - 8);
      ctx.strokeStyle = isWinner ? '#ffcc00' : '#2d2d55';
      ctx.lineWidth = 1;
      ctx.strokeRect(PADDING, y + 4, WIDTH - 2 * PADDING, ROW_HEIGHT - 8);

      // Pick number
      ctx.fillStyle = isWinner ? '#ffcc00' : '#9090b8';
      ctx.font = 'bold 22px ui-monospace, monospace';
      ctx.textAlign = 'right';
      ctx.fillText(`#${row.pickNumber}`, PADDING + 50, y + ROW_HEIGHT / 2);

      // Sprite
      if (sheet) {
        const spriteX = PADDING + 64;
        const spriteY = y + (ROW_HEIGHT - SPRITE_H) / 2;
        ctx.drawImage(sheet, 0, Animation.Idle * SPRITE_H, SPRITE_W, SPRITE_H, spriteX, spriteY, SPRITE_W, SPRITE_H);
      }

      // Name
      ctx.fillStyle = '#f0f0ff';
      ctx.font = isWinner ? 'bold 18px ui-monospace, monospace' : '16px ui-monospace, monospace';
      ctx.textAlign = 'left';
      const name = player ? displayName(player, row.wrestlerId) : `Player ${row.wrestlerId + 1}`;
      ctx.fillText(name, PADDING + 64 + SPRITE_W + 12, y + ROW_HEIGHT / 2);
    });

    // Footer
    ctx.fillStyle = '#9090b8';
    ctx.font = '11px ui-monospace, monospace';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by the Rumble Draft Planner', WIDTH / 2, HEIGHT - 28);

    canvas.toBlob((blob) => resolve(blob), 'image/png');
  });
}

export async function copyBlobToClipboard(blob: Blob): Promise<boolean> {
  if (typeof ClipboardItem === 'undefined' || !navigator.clipboard?.write) return false;
  try {
    await navigator.clipboard.write([new ClipboardItem({ [blob.type]: blob })]);
    return true;
  } catch (e) {
    console.warn('clipboard write failed', e);
    return false;
  }
}
